name: Github Pages Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.7.0

      - name: Install Dependencies
        run: |
          pnpm install --no-frozen-lockfile

      - name: Build
        run: |
          pnpm run build:pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ghb_token }}
          BRANCH: gh-pages
          FOLDER: playground/spa/dist
